[project]
name = "vmprofiler"

[target.vmprofiler]
type = "static"
compile-features = ["cxx_std_20"]

sources = [
    "dependencies/vmprofiler/src/vmprofiles/**.cpp",
    "include/**.hpp"
]

include-directories = [
    "include"
]

link-libraries = [
    "Zydis",
    "linux-pe",
]

compile-definitions = [
    "NOMINMAX"
]

[options]
ZYDIS_BUILD_SHARED_LIB = false
ZYDIS_BUILD_EXAMPLES = false
ZYDIS_BUILD_TOOLS = false
ZYDIS_FUZZ_AFL_FAST = false
ZYDIS_LIBFUZZER = false

[subdir."dependencies/vmprofiler/dependencies/zydis/"]

[target.linux-pe]
type = "interface"
include-directories = ["dependencies/vmprofiler/dependencies/linux-pe/includes/"]
